/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacote;

import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class FrmPainelDeControle extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPainelDeControle.class.getName());

    /**
     * Creates new form FrmPainelDeControle
     */
    public FrmPainelDeControle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSrvDesktop = new javax.swing.JLabel();
        lblSrvDesktopLegenda = new javax.swing.JLabel();
        btnAtivarDesktop = new javax.swing.JToggleButton();
        lblSrvWeb = new javax.swing.JLabel();
        lblSrvWebLegenda = new javax.swing.JLabel();
        btnAtivarWeb = new javax.swing.JToggleButton();
        lblSrvTerceiros = new javax.swing.JLabel();
        lblSrvTerceirosLegenda = new javax.swing.JLabel();
        btnAtivarTerceiros = new javax.swing.JToggleButton();
        lblSrvPublicidade = new javax.swing.JLabel();
        btnAtivarPublicidade = new javax.swing.JToggleButton();
        lblSrvPublicidadeLegenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Painel de Controle");
        setName("frmPainelDeControle"); // NOI18N

        lblSrvDesktop.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSrvDesktop.setText("Serviço Desktop");

        lblSrvDesktopLegenda.setForeground(new java.awt.Color(255, 0, 0));
        lblSrvDesktopLegenda.setText("Inspirado no Whatsapp Desktop");

        btnAtivarDesktop.setText("ATIVAR");
        btnAtivarDesktop.addActionListener(this::btnAtivarDesktopActionPerformed);

        lblSrvWeb.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSrvWeb.setText("Serviço Web");

        lblSrvWebLegenda.setForeground(new java.awt.Color(255, 0, 0));
        lblSrvWebLegenda.setText("Inspirado no Whatsapp Web");

        btnAtivarWeb.setText("ATIVAR");
        btnAtivarWeb.addActionListener(this::btnAtivarWebActionPerformed);

        lblSrvTerceiros.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSrvTerceiros.setText("Serviço Terceiros");

        lblSrvTerceirosLegenda.setForeground(new java.awt.Color(255, 0, 0));
        lblSrvTerceirosLegenda.setText("Softwares de Outras Linguagens");

        btnAtivarTerceiros.setText("ATIVAR");
        btnAtivarTerceiros.addActionListener(this::btnAtivarTerceirosActionPerformed);

        lblSrvPublicidade.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSrvPublicidade.setText("Serviço Publicidade");

        btnAtivarPublicidade.setText("ATIVAR");
        btnAtivarPublicidade.addActionListener(this::btnAtivarPublicidadeActionPerformed);

        lblSrvPublicidadeLegenda.setForeground(new java.awt.Color(255, 0, 0));
        lblSrvPublicidadeLegenda.setText("Envio publicidade multicast");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSrvDesktopLegenda)
                            .addComponent(lblSrvDesktop)
                            .addComponent(lblSrvTerceirosLegenda)
                            .addComponent(lblSrvTerceiros))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(btnAtivarTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnAtivarDesktop, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSrvWeb)
                            .addComponent(lblSrvWebLegenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtivarWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSrvPublicidadeLegenda)
                            .addComponent(lblSrvPublicidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtivarPublicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrvDesktop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSrvDesktopLegenda))
                    .addComponent(btnAtivarDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrvWeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSrvWebLegenda))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnAtivarWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrvTerceiros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSrvTerceirosLegenda))
                    .addComponent(btnAtivarTerceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSrvPublicidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSrvPublicidadeLegenda, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAtivarPublicidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtivarDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarDesktopActionPerformed
        if(btnAtivarDesktop.isSelected()){
        btnAtivarDesktop.setText("DESATIVAR");

        Util.desktopRecepcaoThread = new DesktopRecepcaoThread();
        Thread.ofVirtual().start(Util.desktopRecepcaoThread);

        Util.desktopEnvioThread = new DesktopEnvioThread();
        Thread.ofVirtual().start(Util.desktopEnvioThread);

    }else{
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente parar os serviços para clientes DESKTOP?", "Confirmação", JOptionPane.YES_NO_OPTION);

        if(resposta == JOptionPane.YES_OPTION){
            btnAtivarDesktop.setText("ATIVAR");

            if(Util.desktopRecepcaoThread != null){
                Util.desktopRecepcaoThread.pararServidor();
                Util.desktopRecepcaoThread = null;
            }

            if(Util.desktopEnvioThread != null){
                Util.desktopEnvioThread.pararServidor();
                Util.desktopEnvioThread = null;
            }

        }else{
            btnAtivarDesktop.setSelected(true);
            btnAtivarDesktop.setText("DESATIVAR");
        }
    }
    }//GEN-LAST:event_btnAtivarDesktopActionPerformed

    private void btnAtivarWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarWebActionPerformed
        if(btnAtivarWeb.isSelected() == true){
            btnAtivarWeb.setText("DESATIVAR");
        }else{
            btnAtivarWeb.setText("ATIVAR");
        }
    }//GEN-LAST:event_btnAtivarWebActionPerformed

    private void btnAtivarTerceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarTerceirosActionPerformed
        if(btnAtivarTerceiros.isSelected() == true){
            btnAtivarTerceiros.setText("DESATIVAR");
        }else{
            btnAtivarTerceiros.setText("ATIVAR");
        }
    }//GEN-LAST:event_btnAtivarTerceirosActionPerformed

    private void btnAtivarPublicidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivarPublicidadeActionPerformed
        if(btnAtivarPublicidade.isSelected() == true){
            btnAtivarPublicidade.setText("DESATIVAR");
        }else{
            btnAtivarPublicidade.setText("ATIVAR");
        }
    }//GEN-LAST:event_btnAtivarPublicidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPainelDeControle().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAtivarDesktop;
    private javax.swing.JToggleButton btnAtivarPublicidade;
    private javax.swing.JToggleButton btnAtivarTerceiros;
    private javax.swing.JToggleButton btnAtivarWeb;
    private javax.swing.JLabel lblSrvDesktop;
    private javax.swing.JLabel lblSrvDesktopLegenda;
    private javax.swing.JLabel lblSrvPublicidade;
    private javax.swing.JLabel lblSrvPublicidadeLegenda;
    private javax.swing.JLabel lblSrvTerceiros;
    private javax.swing.JLabel lblSrvTerceirosLegenda;
    private javax.swing.JLabel lblSrvWeb;
    private javax.swing.JLabel lblSrvWebLegenda;
    // End of variables declaration//GEN-END:variables
}
