/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.urna;

/**
 *
 * @author Pedro
 */
public class JFrameApuracao extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameApuracao.class.getName());

    /**
     * Creates new form JFrameApuracao
     */
    public JFrameApuracao() {
        initComponents();
    }
    
    public JFrameApuracao(String resultado){
        initComponents();
        
        String [] linhas = resultado.split("\n");
        
        lblCandidato1.setText(linhas[2]);
        lblCandidato2.setText(linhas[3]);
        lblCandidato3.setText(linhas[4]);
        lblCandidato4.setText(linhas[5]);
        lblBrancos.setText(linhas[6]);
        lblNulos.setText(linhas[7]);
        lblGanhador.setText(linhas[9]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCandidato1 = new javax.swing.JLabel();
        lblCandidato2 = new javax.swing.JLabel();
        lblCandidato3 = new javax.swing.JLabel();
        lblCandidato4 = new javax.swing.JLabel();
        lblBrancos = new javax.swing.JLabel();
        lblNulos = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lblGanhador = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Resultado");

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("RESULTADO");
        lblTitulo.setAlignmentY(0.0F);

        lblCandidato1.setText("Candidato 1:");

        lblCandidato2.setText("Candidato 2:");

        lblCandidato3.setText("Candidato 3:");

        lblCandidato4.setText("Candidato 4:");

        lblBrancos.setText("Brancos:");

        lblNulos.setText("Nulos:");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(this::btnFecharActionPerformed);

        lblGanhador.setForeground(new java.awt.Color(51, 204, 0));
        lblGanhador.setText("Ganhador:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBrancos)
                            .addComponent(lblNulos)
                            .addComponent(lblCandidato3)
                            .addComponent(lblCandidato2)
                            .addComponent(lblCandidato1)
                            .addComponent(lblCandidato4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lblGanhador))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(lblTitulo)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCandidato1)
                .addGap(18, 18, 18)
                .addComponent(lblCandidato2)
                .addGap(18, 18, 18)
                .addComponent(lblCandidato3)
                .addGap(18, 18, 18)
                .addComponent(lblCandidato4)
                .addGap(18, 18, 18)
                .addComponent(lblBrancos)
                .addGap(18, 18, 18)
                .addComponent(lblNulos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGanhador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameApuracao().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBrancos;
    private javax.swing.JLabel lblCandidato1;
    private javax.swing.JLabel lblCandidato2;
    private javax.swing.JLabel lblCandidato3;
    private javax.swing.JLabel lblCandidato4;
    private javax.swing.JLabel lblGanhador;
    private javax.swing.JLabel lblNulos;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
