/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.urna;

import java.io.ObjectOutputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro
 */
public class JFrameUrna extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUrna.class.getName());

    /**
     * Creates new form JFrameUrna
     */
    public JFrameUrna() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoCandidatos = new javax.swing.ButtonGroup();
        lblCandidato = new javax.swing.JLabel();
        rbCandidato1 = new javax.swing.JRadioButton();
        rbCandidato2 = new javax.swing.JRadioButton();
        rbCandidato3 = new javax.swing.JRadioButton();
        rbCandidato4 = new javax.swing.JRadioButton();
        rbBranco = new javax.swing.JRadioButton();
        rbNulo = new javax.swing.JRadioButton();
        btnVotar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Urna Eletrônica");

        lblCandidato.setText("Selecione o candidato:");

        grupoCandidatos.add(rbCandidato1);
        rbCandidato1.setText("Candidato 1");
        rbCandidato1.addActionListener(this::rbCandidato1ActionPerformed);

        grupoCandidatos.add(rbCandidato2);
        rbCandidato2.setText("Candidato 2");
        rbCandidato2.addActionListener(this::rbCandidato2ActionPerformed);

        grupoCandidatos.add(rbCandidato3);
        rbCandidato3.setText("Candidato 3");
        rbCandidato3.addActionListener(this::rbCandidato3ActionPerformed);

        grupoCandidatos.add(rbCandidato4);
        rbCandidato4.setText("Candidato 4");

        grupoCandidatos.add(rbBranco);
        rbBranco.setText("Branco");
        rbBranco.addActionListener(this::rbBrancoActionPerformed);

        grupoCandidatos.add(rbNulo);
        rbNulo.setText("Nulo");

        btnVotar.setText("Votar e aguardar apuração");
        btnVotar.addActionListener(this::btnVotarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("URNA ELETRÔNICA");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCandidato)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbBranco)
                                .addComponent(rbCandidato2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbNulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbCandidato4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCandidato1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(rbCandidato3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnVotar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCandidato)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCandidato1)
                    .addComponent(rbCandidato3))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCandidato2)
                    .addComponent(rbCandidato4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBranco)
                    .addComponent(rbNulo))
                .addGap(36, 36, 36)
                .addComponent(btnVotar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbCandidato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCandidato1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCandidato1ActionPerformed

    private void rbCandidato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCandidato2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCandidato2ActionPerformed

    private void rbCandidato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCandidato3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCandidato3ActionPerformed

    private void rbBrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBrancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBrancoActionPerformed

    private void btnVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotarActionPerformed
        String voto = "";

        if (rbCandidato1.isSelected()) {
            voto = "1";
        }

        if (rbCandidato2.isSelected()) {
            voto = "2";
        }

        if (rbCandidato3.isSelected()) {
            voto = "3";
        }

        if (rbCandidato4.isSelected()) {
            voto = "4";
        }

        if (rbBranco.isSelected()) {
            voto = "5";
        }

        if (rbNulo.isSelected()) {
            voto = "6";
        }

        if (voto.equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção.");
            return;
        }

        try {
            DatagramSocket ds = new DatagramSocket(6667);

            Socket s = new Socket("127.0.0.1", 3322);

            ObjectOutputStream out = new ObjectOutputStream(s.getOutputStream());

            out.writeUTF(voto);
            out.flush();

            out.close();
            s.close();

            byte[] b = new byte[256];
            DatagramPacket pckt = new DatagramPacket(b, b.length);

            ds.receive(pckt);

            String ipGrupo = new String(
                    pckt.getData(),
                    0,
                    pckt.getLength()
            );

            ds.close();

            this.dispose();

            JFrameApuracao instancia = new JFrameApuracao(ipGrupo);
            instancia.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();

            JOptionPane.showMessageDialog(
                    null,
                    "Erro na Urna: " + e.getMessage()
            );
        }
    }//GEN-LAST:event_btnVotarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUrna().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVotar;
    private javax.swing.ButtonGroup grupoCandidatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCandidato;
    private javax.swing.JRadioButton rbBranco;
    private javax.swing.JRadioButton rbCandidato1;
    private javax.swing.JRadioButton rbCandidato2;
    private javax.swing.JRadioButton rbCandidato3;
    private javax.swing.JRadioButton rbCandidato4;
    private javax.swing.JRadioButton rbNulo;
    // End of variables declaration//GEN-END:variables
}
